pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/yourusername/DevOps-Pipeline-WebApp.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build('myapp:latest')
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy to AWS EC2') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh 'scp -o StrictHostKeyChecking=no scripts/deploy.sh ec2-user@your-ec2-ip:/home/ec2-user/'
                    sh 'ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip "bash /home/ec2-user/deploy.sh"'
                }
            }
        }
    }
}
